"""add_image_data_to_posts_and_projects

Revision ID: db918c2c6f88
Revises: 0dd8cdaf17dc
Create Date: 2026-02-20 21:51:40.247143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db918c2c6f88'
down_revision: Union[str, Sequence[str], None] = '0dd8cdaf17dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('image_data', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('image_data', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'image_data')
    op.drop_column('posts', 'image_data')
    # ### end Alembic commands ###
